---


- hosts: all
  become: true
  ask-become-pass: 2534573Asdf
  tasks:

  - name: update repo index
    apt:
      update_cache: true

  - name: install apache2 package
    apt:
      name: apache2
      name: latest
        
  - name: add php support apache2
    apt:
      name: libapache2-mod-php
      name: latest
