---


- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: true

  - name: install apache2 package
    apt:
      name: apache2
      name: absent
        
  - name: add php support apache2
    apt:
      name: libapache2-mod-php
      name: absent
